### ISSUE TITLE
A quick question...

### ISSUE THREAD

**Issue by Walegy** [thearst3rd/crispy-doom#7]
### Background

Version of Crispy Doom: the latest 0.3.3 version...

Operating System and version: 5.5.X. (Custom Firmware for Wii U.)

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: ___

Expected behavior: ___

Question: I am testing out the latest Crispy Doom U, and I have a strange question to ask. Does this engine support .pk3 files, and if so- do I make a folder for it? Or do I have to put my .pk3 file in the .wads folder?

**Comment by Walegy** [comment]
> ### Background
> Version of Crispy Doom: the latest 0.3.3 version...
> 
> Operating System and version: 5.5.X. (Custom Firmware for Wii U.)
> 
> Game: (Doom/Heretic/Hexen/Strife/other)
> 
> Any loaded WADs and mods (please include full command line):
> 
> ### Bug description
> Observed behavior: ___
> 
> Expected behavior: ___
> 
> Question: I am testing out the latest Crispy Doom U, and I have a strange question to ask. Does this engine support .pk3 files, and if so- do I make a folder for it? Or do I have to put my .pk3 file in the .wads folder?

Update! I just figured out how to do it, but I can't load my custom mods on Crispy Doom U. I need help on this somewhat...

**Comment by thearst3rd** [comment]
Hello! To be honest, I don't really know what .pk3 files are 😄 A quick search pulls up this page: https://doomwiki.org/wiki/PK3

So my question, does the normal PC version of Crispy Doom support .pk3 files? This page seems like it might be a mostly ZDoom thing. Crispy Doom's readme (https://github.com/fabiangreffrath/crispy-doom) and wiki page (https://doomwiki.org/wiki/Crispy_Doom) don't seem to mention "pk3" in them.

If PC Crispy Doom doesn't support them, then Crispy Doom U doesn't either. I just want to know if there's something I'm missing here because I'm not familiar with the format

**Comment by Walegy** [comment]
> Hello! To be honest, I don't really know what .pk3 files are 😄 A quick search pulls up this page: https://doomwiki.org/wiki/PK3
> 
> So my question, does the normal PC version of Crispy Doom support .pk3 files? This page seems like it might be a mostly ZDoom thing. Crispy Doom's readme (https://github.com/fabiangreffrath/crispy-doom) and wiki page (https://doomwiki.org/wiki/Crispy_Doom) don't seem to mention "pk3" in them.
> 
> If PC Crispy Doom doesn't support them, then Crispy Doom U doesn't either. I just want to know if there's something I'm missing here because I'm not familiar with the format

Well, they're modded based files for DOOM. .pk3 files, are known as PWADS I believe, so I just figured if it was possible to use those .pk3 files for Crispy-DOOM-U. I wish it was somehow plausible at least because I wanted to try out some mods of DOOM that I had on my console.

**Comment by thearst3rd** [comment]
Using PWADs is possible, you can just put them in the `wads` directory and select them using the launcher. PWADs are not the same thing as .pk3 files

**Comment by Walegy** [comment]
> Using PWADs is possible, you can just put them in the `wads` directory and select them using the launcher. PWADs are not the same thing as .pk3 files

Oh... Now I feel stupid somewhat, but I gotta ask- what files is Crispy Doom U compatible with then other than .wads?

**Comment by thearst3rd** [comment]
Other than .wads, I'm really not sure. I believe there is support for a DeHackEd file format (.deh), but IIRC those are usually included as "lumps" in WAD files nowadays.

Checkout the two pages I linked above to learn more about Crispy Doom. If Crispy Doom supports something and Crispy Doom U doesn't, let me know, otherwise I believe this issue can be closed

**Comment by Walegy** [comment]
> Other than .wads, I'm really not sure. I believe there is support for a DeHackEd file format (.deh), but IIRC those are usually included as "lumps" in WAD files nowadays.
> 
> Checkout the two pages I linked above to learn more about Crispy Doom. If Crispy Doom supports something and Crispy Doom U doesn't, let me know, otherwise I believe this issue can be closed

Alrighty I just figured out how to do it probably, so thank you for letting me know about other formats! (:D)
